name: Build python package and archive wheel

on:
  push:
    branches:
      - main

jobs:
  myjob: 
    name: my job description
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install -r .github/build_requirements.txt 
    - name: Build package
      run: |
        python setup.py bdist_wheel
    - name: Publish whl artefact
      uses: actions/upload-artifact@v3
      with:
        name: package wheel
        path: dist/*.whl