name: Build python package and archive wheel

on:
  push:
    branches:
      - feature/*

jobs:
  myjob: 
    name: my job description
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install wheel 
    - name: Build package
      run: |
        python setup.py bdist_wheel